import type { Job } from "./types"

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "UX Designer, Google Pay",
    company: "Google Inc.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/2048px-Google_%22G%22_Logo.svg.png",
    location: "Shanghai China",
    country: "China",
    views: 240,
    postedTime: "Today",
    jobType: "Full-time",
    applicationsCount: 5,
    salary: {
      amount: 120000,
      currency: "AED",
      period: "year",
    },
    match: {
      type: "top",
    },
    team: "Team",
    department: "Product and Design",
    qualifications: [
      "Bachelor's degree in Design, related field, or equivalent practical experience",
      "7 years of experience as a UX or Interaction Designer",
      "Experience in representing and advocating for UX the and users",
    ],
    experience: ["UX the and users"],
    locationDetails: {
      type: "Onsite",
      place: "Al Mazaj, Sharjah, UAE",
    },
    jobTypes: ["Hybrid", "Onsite"],
    skills: [
      { name: "Photoshop", color: "#0066CC" },
      { name: "Figma", color: "#FF6633" },
      { name: "Adobe Creative Cloud", color: "#33CC33" },
      { name: "Microsoft Office", color: "#CC33CC" },
    ],
    perks: ["Free drinks and snacks", "Competitive salary"],
  },
  {
    id: "2",
    title: "Product Manager - Operating System (Facebook Reality Labs)",
    company: "Facebook",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/2021_Facebook_icon.svg/2048px-2021_Facebook_icon.svg.png",
    location: "Menlo Park, CA",
    country: "USA",
    views: 120,
    postedTime: "3 days ago",
    jobType: "Full-time",
    applicationsCount: 20,
    salary: {
      amount: 100000,
      currency: "AED",
      period: "year",
    },
    match: {
      type: "best",
    },
    team: "Team",
    department: "Product and Design",
  },
  {
    id: "3",
    title: "Senior Product Designer, Customer Journey",
    company: "Twitter",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Logo_of_Twitter.svg/512px-Logo_of_Twitter.svg.png",
    location: "San Francisco",
    country: "USA",
    views: 440,
    postedTime: "5 days ago",
    jobType: "Full-time",
    applicationsCount: 34,
    salary: {
      amount: 100000,
      currency: "AED",
      period: "year",
    },
    match: {
      type: "percentage",
      value: 80,
    },
    team: "Team",
    department: "Product and Design",
  },
  {
    id: "4",
    title: "Senior Product Designer",
    company: "Apple Inc.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1667px-Apple_logo_black.svg.png",
    location: "California, United States",
    country: "USA",
    views: 4320,
    postedTime: "1 week ago",
    jobType: "Part-time",
    applicationsCount: 100,
    salary: {
      amount: 80000,
      currency: "AED",
      period: "year",
    },
    team: "Team",
    department: "Design",
  },
  {
    id: "5",
    title: "UX Designer, Google Pay",
    company: "Google Inc.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/2048px-Google_%22G%22_Logo.svg.png",
    location: "Shanghai China",
    country: "China",
    views: 240,
    postedTime: "Today",
    jobType: "Full-time",
    applicationsCount: 5,
    salary: {
      amount: 120000,
      currency: "AED",
      period: "year",
    },
    team: "Team",
    department: "Product and Design",
  },
  {
    id: "6",
    title: "Senior Product Designer",
    company: "Apple Inc.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1667px-Apple_logo_black.svg.png",
    location: "California, United States",
    country: "USA",
    views: 4320,
    postedTime: "1 week ago",
    jobType: "Part-time",
    applicationsCount: 100,
    salary: {
      amount: 80000,
      currency: "AED",
      period: "year",
    },
    team: "Team",
    department: "Design",
  },
  {
    id: "7",
    title: "UX Designer, Google Pay",
    company: "Google Inc.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/2048px-Google_%22G%22_Logo.svg.png",
    location: "Shanghai China",
    country: "China",
    views: 240,
    postedTime: "Today",
    jobType: "Full-time",
    applicationsCount: 5,
    salary: {
      amount: 120000,
      currency: "AED",
      period: "year",
    },
    team: "Team",
    department: "Product and Design",
  },
]
