export const subscriptionPlans = {
  // businessPlan: {
  //   id: "business-plan",
  //   name: "Business Plan",
  //   price: 100,
  //   totalJobs: 100,
  //   totalInterviewTraining: 0,
  //   totalCoverLetters: 1,
  //   totalATS: 1,
  //   totalAiJobApply: 0,
  //   description: "Apply to 100 jobs",
  // },
  // proPlayerPlan: {
  //   id: "pro-player-plan",
  //   name: "Pro Player Plan",
  //   price: 250,
  //   totalJobs: 100,
  //   totalInterviewTraining: 100,
  //   totalCoverLetters: 1,
  //   totalATS: 1,
  //   totalAiJobApply: 0,
  //   description: "Apply to 100 jobs",
  // },
  aiJobApply: {
    id: "ai-job-apply",
    name: "AI Job Apply",
    price: 200,
    totalJobs: 0,
    totalInterviewTraining: 0,
    totalCoverLetters: 0,
    totalATS: 0,
    totalAiJobApply: 1,
    description: "AI matches your CV to the best 200 jobs from our database and applies on your behalf.",
  },
};